name: MiraclePvP
version: 1.05.1
main: net.miraclepvp.kitpvp.Main
author: AlmostSomeone
description: An Advanced KitPvP System
depend: [WorldGuard, WorldEdit]
commands:
  arena:
    description: Arena command
  map:
    description: Map command
  duel:
    description: Duel command
  top:
    description: Top command
  unbreakable:
    aliases: [unbk]
    description: Unbreakable command
  cosmotokens:
    aliases: [cosmo,tokens,ct]
    description: CosmoTokens command
  rename:
    description: Rename a item
  trail:
    description: Trail command
  cosmetics:
    description: Cosmetics Command
    aliases: [cosmetic]
  suffix:
    description: Suffix Command
  chatcolor:
    description: ChatColor command
  namecolor:
    description: NameColor command
  stats:
    description: Stats command
    aliases: [status]
  kitpvp:
    description: KitPvP command
    aliases: [kp]
  prefix:
    description: Prefix command
  kit:
    description: Kit command
  coins:
    description: Coins command
  guild:
    description: Guild command
    aliases: [g]
  spawnpoints:
    description: Spawnpoint command
  chat:
    description: Chat command
  staffchat:
    description: Staffchat command
  sc:
    description: Alias from staffchat
  supplydrop:
    description: Supplydrop command
    aliases: [sd]
  zone:
    description: Zone command
  booster:
    description: Booster command
    aliases: [boosters]
  fly:
    description: Fly Command for donators
  nick:
    description: Nick Command for donators
  report:
    description: Report Command
  crate:
    description: Crate command
  spawn:
    description: Spawn command
  npc:
    description: NPC Command
  level:
    description: Level Command
  freeze:
    description: Freeze Command
  discord:
    description: Discord Command
  resetstats:
    description: Reset Stats
permissions:
  miraclepvp.*:
    description: Get all permissions
    default: OP
    children:
      miraclepvp.arena: true
      miraclepvp.map: true
      miraclepvp.zone.*: true
      miraclepvp.staffchat.*: true
      miraclepvp.stats.*: true
      miraclepvp.cosmetic.*: true
      miraclepvp.rename: true
      miraclepvp.unbreakable: true
      miraclepvp.kitpvp.*: true
      miraclepvp.prefix: true
      miraclepvp.kit: true
      miraclepvp.coins: true
      miraclepvp.guild.*: true
      miraclepvp.donator.*: true
      miraclepvp.report.*: true
      miraclepvp.freeze.*: true
      miraclepvp.resetstats: true
  miraclepvp.staffchat.*:
    description: Get all permissions for the staffchat system
    default: OP
    children:
      miraclepvp.staffchat.send: true
      miraclepvp.staffchat.receive: true
  miraclepvp.zone.*:
    description: Get all permissions for the zone command
    default: OP
    children:
      miraclepvp.zone: true
      miraclepvp.zone.create: true
      miraclepvp.zone.remove: true
      miraclepvp.zone.list: true
  miraclepvp.stats.*:
    description: Get all permissions for the stats command
    default: OP
    children:
      miraclepvp.stats: true
      miraclepvp.stats.others: true
  miraclepvp.cosmetic.*:
    description: Get all permissions for the cosmetics system
    default: OP
    children:
      miraclepvp.cosmetic.chatcolor: true
      miraclepvp.cosmetic.namecolor: true
      miraclepvp.cosmetic.cosmotokens: true
      miraclepvp.cosmetic.suffix: true
      miraclepvp.cosmetic.trail: true
      miraclepvp.cosmetic.rename: true
  miraclepvp.kitpvp.*:
    description: Get all permissions to manage the kitpvp
    default: OP
    children:
      miraclepvp.kitpvp.setlobby: true
      miraclepvp.kitpvp.lobby: true
      miraclepvp.kitpvp.map: true
      miraclepvp.kitpvp.realname: true
      miraclepvp.kitpvp.setmap: true
      miraclepvp.kitpvp.buildmode: true
      miraclepvp.kitpvp.reload: true
      miraclepvp.kitpvp.gettracker: true
      miraclepvp.kitpvp.getanvil: true
      miraclepvp.kitpvp.save: true
  miraclepvp.guild.*:
    description: Get all permissions for the guild system
    default: OP
    children:
      miraclepvp.guild.create: true
  miraclepvp.donator.*:
    description: Get all donator permissions.
    default: OP
    children:
      miraclepvp.donator.spambypass: true
      miraclepvp.donator.fly: true
      miraclepvp.donator.nick: true
      miraclepvp.donator.autodeploy: true
      miraclepvp.donator.quickselect: true
      miraclepvp.donator.killbroadcast: true
      miraclepvp.donator.streakbroadcast: true
  miraclepvp.report.*:
    description: Get all permissions for the report command.
    default: OP
    children:
      miraclepvp.report.menu: true
      miraclepvp.report.receive: true
  miraclepvp.freeze.*:
    description: Get all permissions to use the freeze command.
    default: OP
    children:
      miraclepvp.freeze: true
      miraclepvp.freeze.bypass: true
      miraclepvp.freeze.alert: true
  miraclepvp.duel.invite:
    description: Get the permission to execute the /duel invite command.
    default: OP
  miraclepvp.kitpvp.map:
    description: Get the permission to execute the /kp map command.
    default: OP
  miraclepvp.kitpvp.realname:
    description: Get the permission to execute /kp realname command.
    default: OP
  miraclepvp.kitpvp.gettracker:
    description: Get the permission to execute the /kp gettracker command.
    default: OP
  miraclepvp.kitpvp.getanvil:
    description: Get the permission to execute the /kp getanvil command.
    default: OP
  miraclepvp.freeze.alert:
    description: Get the permission to get a alert when a frozen player leaves the server
    default: OP
  miraclepvp.freeze:
    description: Get the permission to freeze players
    default: OP
  miraclepvp.freeze.bypass:
    description: Get the permission to bypass the freeze plugin
    default: OP
  miraclepvp.kitpvp.reload:
    description: Get the permission to reload the config
    default: OP
  miraclepvp.report.menu:
    description: Get the permission to open the report GUI
    default: OP
  miraclepvp.report.receive:
    description: Get the permission to receive reports in chat
    default: OP
  miraclepvp.donator.spambypass:
    description: Get the permissions to bypass the spam filter.
    default: OP
  miraclepvp.donator.fly:
    description: Get the permissions to fly in the spawn.
    default: OP
  miraclepvp.donator.nick:
    description: Get the permission to disquise yourself.
    default: OP
  miraclepvp.donator.autodeploy:
    description: Get the permission to use autodeployment
    default: OP
  miraclepvp.donator.quickselect:
    description: Get the permission to use quickselect
    default: OP
  miraclepvp.killbroadcast:
    description: Get the permission to use killbroadcast
    default: OP
  miraclepvp.streakbroadcast:
    description: Get the permission to use streakbroadcast
    default: OP
  miraclepvp.zone:
    description: Get the permission to execute the zone command.
    default: OP
  miraclepvp.zone.create:
    description: Get the permission to create zones
    default: OP
  miraclepvp.zone.remove:
    description: Get the permission to remove zones
    default: OP
  miraclepvp.zone.list:
    description: Get the permission to get a list of all zones
    default: OP
  miraclepvp.staffchat.send:
    description: Get the permission to send staffchat messages.
    default: OP
  miraclepvp.staffchat.receive:
    description: Get the permission to receive staffchat messages.
    default: OP
  miraclepvp.stats:
    description: Get permissions for the stats command
    default: OP
  miraclepvp.stats.others:
    description: Get permissions to watch other players stats
    default: OP
  miraclepvp.cosmetic.chatcolor:
    description: Get the permission for the chatcolor command
    default: OP
  miraclepvp.cosmetic.namecolor:
    description: Get the permission for the namecolor command
    default: OP
  miraclepvp.cosmetic.cosmotokens:
    description: Get the permission to manage players cosmotokens
    default: OP
  miraclepvp.cosmetic.suffix:
    description: Get the permission for the suffix command
    default: OP
  miraclepvp.cosmetic.trail:
    description: Get the permission for the trail command
    default: OP
  miraclepvp.rename:
    description: Get the permission to rename items
    default: OP
  miraclepvp.unbreakable:
    description: Get the permission to make items unbreakable
    default: OP
  miraclepvp.prefix:
    description: Get the permission to manage prefixes
    default: OP
  miraclepvp.kit:
    description: Get the permission to manage kits
    default: OP
  miraclepvp.kitpvp.setlobby:
    description: Get the permission to set the lobby location
    default: OP
  miraclepvp.kitpvp.lobby:
    description: Get the permission to execute the lobby command
    default: OP
  miraclepvp.kitpvp.setmap:
    description: Get the permission to set the map center location
    default: OP
  miraclepvp.kitpvp.buildmode:
    description: Get the permission to toggle buildmode
    default: OP
  miraclepvp.coins:
    description: Get the permission to manage coins
    default: OP
  miraclepvp.guild.create:
    description: Get the permission to create a guild
    default: OP
  miraclepvp.resetstats:
    description: Reset someone's stats
    default: OP