name: PremiumPvP
version: 1.10.1
main: net.miraclepvp.kitpvp.Main
author: Debug_
description: An Advanced KitPvP System
softdepend: [WorldGuard, WorldEdit]
website: https://spigotmc.org/resources/46196
commands:
  friends:
    description: Friends command
    aliases: [friend, f]
  message:
    description: Message command
    aliases: [msg, m]
  reply:
    description: Reply command
    aliases: [rep, r]
  hidechat:
    description: Hidechat command
    aliases: [hc]
  anvil:
    description: Anvil command
  arena:
    description: Arena command
  map:
    description: Map command
  duel:
    description: Duel command
    aliases: [1v1]
  top:
    description: Top command
  unbreakable:
    aliases: [unbk]
    description: Unbreakable command
  cosmotokens:
    aliases: [cosmo,tokens,ct]
    description: CosmoTokens command
  rename:
    description: Rename a item
  trail:
    description: Trail command
  cosmetics:
    description: Cosmetics Command
    aliases: [cosmetic]
  suffix:
    description: Suffix Command
  chatcolor:
    description: ChatColor command
  namecolor:
    description: NameColor command
  stats:
    description: Stats command
    aliases: [status]
  kitpvp:
    description: KitPvP command
    aliases: [kp]
  prefix:
    description: Prefix command
  kit:
    description: Kit command
  coins:
    description: Coins command
  guild:
    description: Guild command
    aliases: [g]
  spawnpoints:
    description: Spawnpoint command
  chat:
    description: Chat command
  staffchat:
    description: Staffchat command
  sc:
    description: Alias from staffchat
  supplydrop:
    description: Supplydrop command
    aliases: [sd]
  zone:
    description: Zone command
  booster:
    description: Booster command
    aliases: [boosters]
  fly:
    description: Fly Command for donators
  report:
    description: Report Command
  crate:
    description: Crate command
  spawn:
    description: Spawn command
  freeze:
    description: Freeze Command
  discord:
    description: Discord Command
  resetstats:
    description: Reset Stats
permissions:
  premiumpvp.*:
    description: Get all permissions
    default: OP
    children:
      premiumpvp.arena: true
      premiumpvp.map: true
      premiumpvp.zone.*: true
      premiumpvp.staffchat.*: true
      premiumpvp.stats.*: true
      premiumpvp.cosmetic.*: true
      premiumpvp.rename: true
      premiumpvp.unbreakable: true
      premiumpvp.kitpvp.*: true
      premiumpvp.prefix: true
      premiumpvp.kit: true
      premiumpvp.coins: true
      premiumpvp.guild.*: true
      premiumpvp.donator.*: true
      premiumpvp.report.*: true
      premiumpvp.freeze.*: true
      premiumpvp.resetstats: true
      premiumpvp.msg.staff: true
  premiumpvp.staffchat.*:
    description: Get all permissions for the staffchat system
    default: OP
    children:
      premiumpvp.staffchat.send: true
      premiumpvp.staffchat.receive: true
  premiumpvp.zone.*:
    description: Get all permissions for the zone command
    default: OP
    children:
      premiumpvp.zone: true
      premiumpvp.zone.create: true
      premiumpvp.zone.remove: true
      premiumpvp.zone.list: true
  premiumpvp.stats.*:
    description: Get all permissions for the stats command
    default: OP
    children:
      premiumpvp.stats: true
      premiumpvp.stats.others: true
  premiumpvp.cosmetic.*:
    description: Get all permissions for the cosmetics system
    default: OP
    children:
      premiumpvp.cosmetic.chatcolor: true
      premiumpvp.cosmetic.namecolor: true
      premiumpvp.cosmetic.cosmotokens: true
      premiumpvp.cosmetic.suffix: true
      premiumpvp.cosmetic.trail: true
      premiumpvp.cosmetic.rename: true
  premiumpvp.kitpvp.*:
    description: Get all permissions to manage the kitpvp
    default: OP
    children:
      premiumpvp.kitpvp.setlobby: true
      premiumpvp.kitpvp.lobby: true
      premiumpvp.kitpvp.map: true
      premiumpvp.kitpvp.realname: true
      premiumpvp.kitpvp.setmap: true
      premiumpvp.kitpvp.buildmode: true
      premiumpvp.kitpvp.reload: true
      premiumpvp.kitpvp.gettracker: true
      premiumpvp.kitpvp.save: true
  premiumpvp.guild.*:
    description: Get all permissions for the guild system
    default: OP
    children:
      premiumpvp.guild.create: true
  premiumpvp.donator.*:
    description: Get all donator permissions.
    default: OP
    children:
      premiumpvp.donator.spambypass: true
      premiumpvp.donator.fly: true
      premiumpvp.donator.autodeploy: true
      premiumpvp.donator.quickselect: true
      premiumpvp.donator.killbroadcast: true
      premiumpvp.donator.streakbroadcast: true
  premiumpvp.report.*:
    description: Get all permissions for the report command.
    default: OP
    children:
      premiumpvp.report.menu: true
      premiumpvp.report.receive: true
  premiumpvp.freeze.*:
    description: Get all permissions to use the freeze command.
    default: OP
    children:
      premiumpvp.freeze: true
      premiumpvp.freeze.bypass: true
      premiumpvp.freeze.alert: true
  premiumpvp.msg.staff:
    description: Get the permissions to send and receive messages without being friends
    default: OP
  premiumpvp.duel.invite:
    description: Get the permission to execute the /duel invite command.
    default: OP
  premiumpvp.kitpvp.map:
    description: Get the permission to execute the /kp map command.
    default: OP
  premiumpvp.kitpvp.realname:
    description: Get the permission to execute /kp realname command.
    default: OP
  premiumpvp.kitpvp.gettracker:
    description: Get the permission to execute the /kp gettracker command.
    default: OP
  premiumpvp.freeze.alert:
    description: Get the permission to get a alert when a frozen player leaves the server
    default: OP
  premiumpvp.freeze:
    description: Get the permission to freeze players
    default: OP
  premiumpvp.freeze.bypass:
    description: Get the permission to bypass the freeze plugin
    default: OP
  premiumpvp.kitpvp.reload:
    description: Get the permission to reload the config
    default: OP
  premiumpvp.report.menu:
    description: Get the permission to open the report GUI
    default: OP
  premiumpvp.report.receive:
    description: Get the permission to receive reports in chat
    default: OP
  premiumpvp.donator.spambypass:
    description: Get the permissions to bypass the spam filter.
    default: OP
  premiumpvp.donator.fly:
    description: Get the permissions to fly in the spawn.
    default: OP
  premiumpvp.donator.autodeploy:
    description: Get the permission to use autodeployment
    default: OP
  premiumpvp.donator.quickselect:
    description: Get the permission to use quickselect
    default: OP
  premiumpvp.killbroadcast:
    description: Get the permission to use killbroadcast
    default: OP
  premiumpvp.streakbroadcast:
    description: Get the permission to use streakbroadcast
    default: OP
  premiumpvp.zone:
    description: Get the permission to execute the zone command.
    default: OP
  premiumpvp.zone.create:
    description: Get the permission to create zones
    default: OP
  premiumpvp.zone.remove:
    description: Get the permission to remove zones
    default: OP
  premiumpvp.zone.list:
    description: Get the permission to get a list of all zones
    default: OP
  premiumpvp.staffchat.send:
    description: Get the permission to send staffchat messages.
    default: OP
  premiumpvp.staffchat.receive:
    description: Get the permission to receive staffchat messages.
    default: OP
  premiumpvp.stats:
    description: Get permissions for the stats command
    default: OP
  premiumpvp.stats.others:
    description: Get permissions to watch other players stats
    default: OP
  premiumpvp.cosmetic.chatcolor:
    description: Get the permission for the chatcolor command
    default: OP
  premiumpvp.cosmetic.namecolor:
    description: Get the permission for the namecolor command
    default: OP
  premiumpvp.cosmetic.cosmotokens:
    description: Get the permission to manage players cosmotokens
    default: OP
  premiumpvp.cosmetic.suffix:
    description: Get the permission for the suffix command
    default: OP
  premiumpvp.cosmetic.trail:
    description: Get the permission for the trail command
    default: OP
  premiumpvp.rename:
    description: Get the permission to rename items
    default: OP
  premiumpvp.unbreakable:
    description: Get the permission to make items unbreakable
    default: OP
  premiumpvp.prefix:
    description: Get the permission to manage prefixes
    default: OP
  premiumpvp.kit:
    description: Get the permission to manage kits
    default: OP
  premiumpvp.kitpvp.setlobby:
    description: Get the permission to set the lobby location
    default: OP
  premiumpvp.kitpvp.lobby:
    description: Get the permission to execute the lobby command
    default: OP
  premiumpvp.kitpvp.setmap:
    description: Get the permission to set the map center location
    default: OP
  premiumpvp.kitpvp.buildmode:
    description: Get the permission to toggle buildmode
    default: OP
  premiumpvp.coins:
    description: Get the permission to manage coins
    default: OP
  premiumpvp.guild.create:
    description: Get the permission to create a guild
    default: OP
  premiumpvp.resetstats:
    description: Reset someone's stats
    default: OP