delay: 300
servername: someServer
messages:
  - 'Set endless messages <3 in the config'
  - '&c&m-----------------------------------------------------<br>&f%server_name%<br> <br>&7Test message<br>&c&m-----------------------------------------------------'

