name: MiraclePvP
version: 1.0
main: me.sahustei.miraclepvp.Main
author: Sahustei
website: www.sahustei.nl
description: An Advanced KitPvP System
commands:
  unbreakable:
    aliases: [unbk]
    description: Unbreakable command
  cosmotokens:
    aliases: [cosmo,tokens,ct]
    description: CosmoTokens command
  rename:
    description: Rename a item
  trail:
    description: Trail command
  cosmetics:
    description: Cosmetics Command
    aliases: [cosmetic,cosmo]
  suffix:
    description: Suffix Command
  freeze:
    description: Freeze players